namespace ConsoleApp2.View;

public enum CalendarMenuResponses
{
    YOU_DO_NOT_HAVE_ACCESS_TO_DO_THIS,
    EVENT_ADDED_SUCCESSFULLY,
    INVALID_TITLE,
    INVALID_START_DATE,
    INVALID_END_DATE,
    THERE_IS_ANOTHER_EVENT_WITH_THIS_TITLE,
    TASK_ADDED_SUCCESSFULLY,
    THERE_IS_ANOTHER_TASK_WITH_THIS_TITLE,
    THERE_IS_NO_EVENT_WITH_THIS_TITLE,
    THERE_IS_NO_TASK_WITH_THIS_TITLE,
    EVENT_EDITED,
    TASK_EDITED,
    EVENT_DELETED_SUCCESSFULLY,
    TASK_DELETED_SUCCESSFULLY,
    INVALID_COMMAND,
    INVALID_FIELD,
    INVALID_START_TIME,
    INVALID_END_TIME
}