namespace ConsoleApp2.View;

public enum MainMenuResponses
{
    CALENDAR_CREATED_SUCCESSFULLY,
    INVALID_TITLE,
    INVALID_ID,
    CALENDAR_OPENED_SUCCESSFULLY,
    THERE_IS_NO_CALENDAR_WITH_THIS_ID,
    YOU_HAVE_NO_CALENDAR_WITH_THIS_ID,
    CALENDAR_ENABLED_SUCCESSFULLY,
    CALENDAR_DISABLED_SUCCESSFULLY,
    CALENDAR_DELETED,
    YOU_DO_NOT_HAVE_ACCESS_TO_DELETE_THIS_CALENDAR,
    CALENDAR_REMOVED,
    OK,
    CALENDAR_TITLE_EDITED,
    YOU_DO_NOT_HAVE_ACCESS_TO_EDIT_THIS_CALENDAR,
    CALENDAR_SHARED,
    YOU_DO_NOT_HAVE_ACCESS_TO_SHARE_THIS_CALENDAR,
    INVALID_USERNAME,
    NO_USER_EXISTS_WITH_THIS_USERNAME,
    LOGOUT_SUCCESSFUL

}