// <auto-generated />
using System;
using KiaRecorder.Data.KiarashRecorder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiaRecorder.Migrations
{
    [DbContext(typeof(KiaRecorderContext))]
    [Migration("20220305070958_final")]
    partial class final
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KiaRecorder.Models.Recorder", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryId"), 1L, 1);

                    b.Property<int>("Random")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timer")
                        .HasColumnType("datetime2");

                    b.HasKey("EntryId");

                    b.ToTable("Reecorders");
                });
#pragma warning restore 612, 618
        }
    }
}
